-- =====================================================================
-- Nebula — database schema (MySQL / MariaDB on Hostinger)
--
-- Written to migrate cleanly to Postgres (e.g. Supabase) later:
--   1. Standard types only. No ENUM, no UNSIGNED. Allowed values are
--      enforced with CHECK constraints (standard SQL, works in Postgres).
--   2. IDs are UUIDs (CHAR(36)), generated by the app, not AUTO_INCREMENT.
--   3. File locations are RELATIVE paths (uploads/2026/10/abc.png).
--      The base URL lives in one backend setting.
--   4. All times are UTC, stored as DATETIME and set by the app
--      (DATETIME, not TIMESTAMP, so MySQL never converts time zones).
--   5. Only the backend API talks to this database.
--
-- Notes for a future move to Postgres:
--   - TINYINT(1) / BOOLEAN  -> boolean   (pgloader converts automatically)
--   - MEDIUMTEXT            -> text
--   - DATETIME              -> timestamptz (values are already UTC)
-- =====================================================================

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------
-- R1 + R2: core tables
-- ---------------------------------------------------------------------

-- Single user for now, but the app is on the public internet, so it needs a login.
CREATE TABLE users (
  id             CHAR(36)     NOT NULL,
  email          VARCHAR(255) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL,
  created_at     DATETIME     NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login sessions, so a server restart doesn't sign you out.
CREATE TABLE sessions (
  sid         VARCHAR(128) NOT NULL,
  data        TEXT         NOT NULL,
  expires_at  DATETIME     NOT NULL,
  PRIMARY KEY (sid),
  KEY ix_sessions_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Groups items shared together ("3 entries that stay linked").
CREATE TABLE capture_sessions (
  id          CHAR(36)     NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  name        VARCHAR(255) NULL,
  created_at  DATETIME     NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One saved thing: screenshot, link, video, audio, document or note.
CREATE TABLE entries (
  id                     CHAR(36)      NOT NULL,
  user_id                CHAR(36)      NOT NULL,
  session_id             CHAR(36)      NULL,
  content_type           VARCHAR(20)   NOT NULL,
  title                  VARCHAR(255)  NULL,      -- blank = filled from extracted text later
  why_saved              TEXT          NULL,
  intent                 VARCHAR(20)   NULL,
  source_url             VARCHAR(2048) NULL,
  cover_path             VARCHAR(512)  NULL,      -- relative path; defaults to the asset or link preview
  extract_mode           VARCHAR(10)   NOT NULL DEFAULT 'text',
  extract_status         VARCHAR(20)   NOT NULL DEFAULT 'pending',
  extracted_text         MEDIUMTEXT    NULL,      -- OCR text or transcript
  listen_only_ok         BOOLEAN       NOT NULL DEFAULT FALSE,  -- "OK to just listen"
  on_dashboard           BOOLEAN       NOT NULL DEFAULT TRUE,   -- on by default, per your note
  added_to_dashboard_at  DATETIME      NULL,
  status                 VARCHAR(20)   NOT NULL DEFAULT 'new',
  created_at             DATETIME      NOT NULL,
  updated_at             DATETIME      NOT NULL,
  PRIMARY KEY (id),
  KEY ix_entries_dashboard (user_id, on_dashboard, added_to_dashboard_at),
  KEY ix_entries_created (user_id, created_at),
  CONSTRAINT fk_entries_user    FOREIGN KEY (user_id)    REFERENCES users (id)            ON DELETE CASCADE,
  CONSTRAINT fk_entries_session FOREIGN KEY (session_id) REFERENCES capture_sessions (id) ON DELETE SET NULL,
  CONSTRAINT ck_entries_type    CHECK (content_type IN ('image','video','document','url','audio','note')),
  CONSTRAINT ck_entries_intent  CHECK (intent IS NULL OR intent IN ('watch','read','try','research','reference')),
  CONSTRAINT ck_entries_xmode   CHECK (extract_mode IN ('text','code','none')),
  CONSTRAINT ck_entries_xstatus CHECK (extract_status IN ('pending','done','failed','skipped')),
  CONSTRAINT ck_entries_status  CHECK (status IN ('new','done','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The actual files. Several per entry when "1 entry with 3 images" is chosen.
CREATE TABLE entry_assets (
  id          CHAR(36)     NOT NULL,
  entry_id    CHAR(36)     NOT NULL,
  path           VARCHAR(512) NOT NULL,   -- relative path, e.g. 2026/10/<id>.png
  original_name  VARCHAR(255) NULL,       -- the file's name on your phone, for display/download
  mime_type      VARCHAR(100) NOT NULL,
  size_bytes  BIGINT       NOT NULL,
  position    INT          NOT NULL DEFAULT 0,
  created_at  DATETIME     NOT NULL,
  PRIMARY KEY (id),
  KEY ix_assets_entry (entry_id, position),
  CONSTRAINT fk_assets_entry FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tags are stored lowercase without the "#"; the UI adds it.
CREATE TABLE tags (
  id          CHAR(36)    NOT NULL,
  user_id     CHAR(36)    NOT NULL,
  name        VARCHAR(64) NOT NULL,
  created_at  DATETIME    NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tags_name (user_id, name),
  CONSTRAINT fk_tags_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Many-to-many: an entry has many tags, a tag has many entries.
CREATE TABLE entry_tags (
  entry_id  CHAR(36) NOT NULL,
  tag_id    CHAR(36) NOT NULL,
  added_at  DATETIME NOT NULL,       -- powers the "Recent" tag chips
  PRIMARY KEY (entry_id, tag_id),
  KEY ix_entry_tags_tag (tag_id),
  CONSTRAINT fk_et_entry FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE CASCADE,
  CONSTRAINT fk_et_tag   FOREIGN KEY (tag_id)   REFERENCES tags (id)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- To-dos and reminders. A task can stand alone or point at an entry.
CREATE TABLE tasks (
  id          CHAR(36)     NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  entry_id    CHAR(36)     NULL,
  title       VARCHAR(255) NOT NULL,
  notes       TEXT         NULL,
  due_at      DATETIME     NULL,     -- a task with a due date is a reminder
  done        BOOLEAN      NOT NULL DEFAULT FALSE,
  done_at     DATETIME     NULL,
  created_at  DATETIME     NOT NULL,
  updated_at  DATETIME     NOT NULL,
  PRIMARY KEY (id),
  KEY ix_tasks_today (user_id, done, due_at),
  CONSTRAINT fk_tasks_user  FOREIGN KEY (user_id)  REFERENCES users (id)   ON DELETE CASCADE,
  CONSTRAINT fk_tasks_entry FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- R2.5: morning news
-- ---------------------------------------------------------------------

CREATE TABLE news_topics (
  id          CHAR(36)     NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  query       VARCHAR(500) NOT NULL,
  source      VARCHAR(20)  NOT NULL DEFAULT 'web',
  active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  DATETIME     NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_topics_user  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT ck_topics_source CHECK (source IN ('web','youtube'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE news_items (
  id              CHAR(36)      NOT NULL,
  topic_id        CHAR(36)      NOT NULL,
  title           VARCHAR(500)  NOT NULL,
  url             VARCHAR(2048) NOT NULL,
  url_hash        CHAR(64)      NOT NULL,  -- SHA-256 of url, so the same link is never shown twice
  source_name     VARCHAR(255)  NULL,
  thumbnail_url   VARCHAR(2048) NULL,
  summary         TEXT          NULL,
  found_at        DATETIME      NOT NULL,
  status          VARCHAR(20)   NOT NULL DEFAULT 'new',
  saved_entry_id  CHAR(36)      NULL,      -- set when "Save" turns it into an entry
  PRIMARY KEY (id),
  UNIQUE KEY uq_news_url (topic_id, url_hash),
  KEY ix_news_status (status, found_at),
  CONSTRAINT fk_news_topic FOREIGN KEY (topic_id)       REFERENCES news_topics (id) ON DELETE CASCADE,
  CONSTRAINT fk_news_entry FOREIGN KEY (saved_entry_id) REFERENCES entries (id)     ON DELETE SET NULL,
  CONSTRAINT ck_news_status CHECK (status IN ('new','saved','dismissed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- R5: playlists
-- ---------------------------------------------------------------------

CREATE TABLE playlists (
  id          CHAR(36)     NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  name        VARCHAR(255) NOT NULL,
  created_at  DATETIME     NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_playlists_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE playlist_items (
  playlist_id  CHAR(36) NOT NULL,
  entry_id     CHAR(36) NOT NULL,
  position     INT      NOT NULL,
  played       BOOLEAN  NOT NULL DEFAULT FALSE,
  added_at     DATETIME NOT NULL,
  PRIMARY KEY (playlist_id, entry_id),
  KEY ix_pi_order (playlist_id, position),
  CONSTRAINT fk_pi_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE,
  CONSTRAINT fk_pi_entry    FOREIGN KEY (entry_id)    REFERENCES entries (id)   ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
